### PR TITLE
Work in Node 7 and Node 9

### PR DESCRIPTION
**Pull request by deinok**

### CODE REVIEW

**Comment by biancode** [comment]
Did you check if the serialport is fully compatible to these versions of node?

**Comment by biancode** [comment]
serialport normaly supporting just LTS versions ...

**Comment by deinok** [comment]
Yes, I have test it. The 7 and 9 should not be a problem.

**Comment by biancode** [comment]
I'm sorry but it will stay in supported LTS versions

grafik

**Pull request closed without merging**
