### PR TITLE
Modbus getter dynamic message support

### PR DESCRIPTION
**Pull request by SuperJojo2001**
Modbus getter supports now msg.payload based Modbus read requests

msg.payload.unitid = Modbus TCP Unit ID / RTU server address
msg.paylad.fc = numeric value of function code to be used (1,2,3,4)
msg.payload.address = register address to be read
msg.payload.quantity = number of values to be read

If msg.payload it not set, function falls back to default values of the config node

### CODE REVIEW

**Comment by biancode** [comment]
Why do you want to send values in value of msg, if you get it from output one. If you need it like that way,  use a function to concat all in one payload with a function node, please.

**Comment by SuperJojo2001** [comment]
@biancode I have to explain our typical Modbus RTU applications we are faced with since 30 years.

We have a gateway device http://www.hilscher.com/de/produkte/produktgruppen/industrie-40-industrial-internet/netiot-edge/nt-ijcx-gb-repns/? that connects to Cloud Systems like IBM, SAP, Microsoft primarily. This gateway includes Node-Red which is doing the "data wiring" and this gateway has also RS232 and RS485 interfaces. On these serial interfaces we want to drive Modbus RTU via Node-RED. 

The typical Modbus RTU applications we are faced with from real life applications are: most customer's Modbus RTU installations consists of 10 to 20 Modbus RTU slave on RS485. They are all of the same type. And all these devices have 20 to 30 analog registers at different positions we need to read periodically from all devices. This make 20 * 30 = 600 Modbus RTU messages. So in the current "Modbus Getter" as it is today I need to place 600 "Modbus Getter" or 600 "Modbus Read" to get all this information cause configuration of "Modbus-Client" config node is static.

This is why I am looking for a programmable "Modbus Getter" via msg.payload to take control of the Modbus Message it is sending (with all respect of the node how it was working before my changes, not to influence existing flows)

With the "Modbus Getter" node of my pull request I can now put this code in a single function node:

for(slave=1; slave < 20; slave++) {
    for(register = 1; register < 30; register++ ) {
        var msg = {};
        msg.payload = {"fc":3, "unitid":slave,"address":register,"quantity":1};
        node.send(msg)
    }
}

It is injecting and queuing 600 message into "Modbus Getter" node to 20 slave with 30 registers each and Modbus Getter sends one after the other. Look this is the result using just one single "Modbus Getter" node.

poll

**Comment by SuperJojo2001** [comment]
Now I want to explain to you why in node's output the value is needed in one message along with the fc,address,unitid,quantity. The response value itself needs to be synchronous to these parameters. If I would do it like you propose...taking output 1 and concat with output 3 both message will never be synchronous due to asynchronous msg handling of node-red itself in case multiple modbus message are active in "Modbus Getter" node the same time. I agree that taking output 1 and concat to output 3 will work if I have one constant message setup active in config node like "Modbus Getter" works today.

**Comment by SuperJojo2001** [comment]
I modified the code in that way to check for incoming msg.payload without save try {} catch{} construction now

**Comment by biancode** [comment]
did it my way ... but thank you for info and try

**Pull request closed without merging**
