### PR TITLE
added serial client type

### PR DESCRIPTION
**Pull request by iurly**
Tried some basic implementation. Seems to work for me, but expect it to be broken. ;-)

For testing, you can use my setup described in: 
https://github.com/Cloud-Automation/node-modbus/issues/27

Notice how you also need a couple of patches in my pull request for jsmodbus (not merget yet, as of now):
https://github.com/Cloud-Automation/node-modbus/pull/37

### CODE REVIEW

**Comment by biancode** [comment]
I'll review it in the next few days, but travis have failed to build

**Comment by biancode** [comment]
OK, please pull the master and test it. I've done some review and code cleaning and may it works. I've no time in the next few days to test it, but next week it should be ready to release. Please post your test results in text if it works!

**Comment by iurly** [comment]
Hi,
thanks for merging!
I pulled the master, it seems to work fine.
I'm using the test setup I described in the issue I mentioned above (socat + patched pymodslave).

**Comment by k30r88** [comment]
@iurly and @biancode  I have difficulty testing this modbus serial option. We are interested to test Modbus RTU over serial.  Is the modbus serial implementation here is Modbus TCP over serial ? Or perhaps Modbus ASCII over serial ?

**Comment by iurly** [comment]
@k30r88 it is Modbus RTU over serial. Beware this feature was only added very recently, so you need the latest trunk, plus some changes in Cloud-Automation/node-modbus#37.

**Comment by k30r88** [comment]
@iurly, does it mean I need to get the appropriate jsmodbus lib that included changes in Cloud-Automation/node-modbus#37. ? Has this change been merge into the latest jsmodbus lib ?

**Pull request merged**
